
[[redirects]]
from = "/*"
to = "/"
status = 200
headers = { Access-Control-Allow-Origin = "*"}

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"
[headers.values]
Access-Control-Allow-Origin= "**"